roomtone:
  global:
    overloadThresh: -6.0
    resetThresh: -32.0
    adcInput: 1
    digitalGain: 1.0
    outputGain: 0.0
    maxDelay: 300000
    baseDelayMin: 500.
    baseDelayMax: 1000.
    baseDelayInterval: 0.05
    enableRandomInterval: 0
    fullscreen: 1
  channel1:
    output: 1
    interval: 2
  channel2:
    output: 2
    interval: 3
  channel3:
    output: 3
    interval: 3
  channel4:
    output: 4
    interval: 4
